language: objective-c

script:
  - xcodebuild clean -project WAMSimpleDataSource.xcodeproj
  - xctool -project WAMSimpleDataSource.xcodeproj -scheme WAMSimpleDataSource test -sdk iphonesimulator GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
  - bash <(curl -s https://codecov.io/bash)
branches:
  only:
  - master
  - develop
